#!/usr/bin/with-contenv bash

# copy config
[[ ! -f /config/settings.json ]] && cp \
	/defaults/settings.json /config/settings.json

# copy blocklist-update script
[[ ! -f /config/blocklist-update.sh ]] && cp \
	/defaults/blocklist-update.sh /config/blocklist-update.sh

# permissions
chown abc:abc \
	/config/settings.json \
	/config/blocklist-update.sh \
	/watch

chmod 755 /config/blocklist-update.sh
